version: 1.0.{build}
image: Visual Studio 2017
before_build: nuget restore
build:
  verbosity: minimal
  project: Foq.sln
test_script:
  - cmd: dotnet msbuild /m Tests/tests.proj
artifacts:
  - path: 'Foq\bin\**\*.nupkg'